module.exports = {
  // badbot: require('./players/badbot'),
  random: require('./players/randombot'),
  // random2: require('./players/randombot'),
  tis_scratch: require('./players/tis_scratch'),
  // codingpains: require('./players/codingpains.js'),
  // manuelmhtr: require('./players/manuelmhtr.js'),
  // ericku: require('./players/ericku.js'),
  siegfried: require('./players/siegfried.js'),
  horror: require('./players/horror.js'),
  elperron: require('./players/elperron.js'),
  yuno: require('./players/yuno.js'),
  // xmontoya: require('./players/xmontoya.js'),
  // margeux: require('./players/margeux.js'),
  // hamza: require('./players/hamzaplay.js'),
  // codingpains2: require('./players/codingpains.js'),
  // manuelmhtr2: require('./players/manuelmhtr.js'),
  // ericku2: require('./players/ericku.js'),
  // siegfried2: require('./players/siegfried.js'),
  // horror2: require('./players/horror.js'),
  // elperron2: require('./players/elperron.js'),
  // yuno2: require('./players/yuno.js'),
  // xmontoya2: require('./players/xmontoya.js'),
  // margeux2: require('./players/margeux.js'),
  // hamza2: require('./players/hamzaplay.js'),
  // codingpains3: require('./players/codingpains.js'),
  // manuelmhtr3: require('./players/manuelmhtr.js'),
  // ericku3: require('./players/ericku.js'),
  // siegfried3: require('./players/siegfried.js'),
  // horror3: require('./players/horror.js'),
  // elperron3: require('./players/elperron.js'),
  // yuno3: require('./players/yuno.js'),
  // xmontoya3: require('./players/xmontoya.js'),
  // margeux3: require('./players/margeux.js'),
  // hamza3: require('./players/hamzaplay.js'),
  // codingpains4: require('./players/codingpains.js'),
  // manuelmhtr4: require('./players/manuelmhtr.js'),
  // ericku4: require('./players/ericku.js'),
  // siegfried4: require('./players/siegfried.js'),
  // horror4: require('./players/horror.js'),
  // elperron4: require('./players/elperron.js'),
  // yuno4: require('./players/yuno.js'),
  // xmontoya4: require('./players/xmontoya.js'),
  // margeux4: require('./players/margeux.js'),
  // hamza4: require('./players/hamzaplay.js')
};
